export const ADD_IMAGES = 'ADD_IMAGES';
export const CLEAR_IMAGES = 'CLEAR_IMAGES';
export const TOGGLE_DIALOG = 'TOGGLE_DIALOG';
export const SET_VISIBILITY_ADD = 'SET_VISIBILITY_ADD';
export const SIGN_IN_GOOGLE = 'SIGN_IN_GOOGLE'
export const SIGN_OUT_GOOGLE = 'SIGN_OUT_GOOGLE'